### ISSUE TITLE
Graceful recovery from failed solution attempts

### ISSUE THREAD

**Issue by dextorious** [JuliaDiffEq/DiffEqMonteCarlo.jl#14]
For Monte Carlo problems with random initial states, it is often the case in practice that some of the states are not viable in the sense that they do not permit valid solutions to the underlying equations. Since sometimes manually filtering out such states is difficult and their existence does not necessarily impair the validity of the Monte Carlo analysis, it would be desirable to have an optional ability to avoid throwing solver errors and halting the entire ensemble simulation.

As discussed in the Gitter chat, a reasonable API solution could consist of letting the user optionally pass a callback via `on_failure(prob,failed_prob,i)`. A reasonable generic callback of this kind could, for instance, consist of adding an additional simulation to the ensemble to compensate for the failed one and saving the failed initial state to some data structure for later analysis.

**Comment by ChrisRackauckas** [comment]
From today. Instead of expanding the interface a bunch, we can make `output_func` handle this.

```julia
output_func(sol,i)
  # make some output value `out`
  out,rerun,save
end
```

`rerun` is a boolean for whether to run another time (does it need to change the problem? How?), and `save` is a boolean for whether to save this run.

**Comment by ChrisRackauckas** [comment]
I made it just:

```julia
output_func(sol,i)
  # make some output value `out`
  out,rerun
end
```

Save would actually be far too hard in many cases, and I notice that it's very rare you'd want to but `rerun` and save the failed run.

**Comment by ChrisRackauckas** [comment]
Done. Will need a new DiffEqBase version for this release.
