### ISSUE TITLE
Callbacks in Monte Carlo simulations

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/DiffEqMonteCarlo.jl#18]
Hi @ChrisRackauckas !

I was looking how to use the `DiffEqMonteCarlo` to perform the Monte Carlo analysis of my simulator, since there are a lot of good analysis tools here! However, I could not find how can I configure callbacks in each run of the Monte Carlo simulation. Is that possible?

**Comment by ChrisRackauckas** [comment]
All keyword arguments are forwarded to the solver, so just use it as you normally would. In addition, you're able to add callbacks to a problem type, so you can add `callback = ...` in `ODEProblem`, and make use of this in the `prob_func`. More tools will be developed soon for individualizing runs though, but that should be good for now at least.

**Comment by ronisbr** [comment]
So is this the right usage:

```
prob = ODEProblem(dyn_eq, u0, (0.0, tf))
sol = solve(monte_prob, Tsit5(), num_monte=100, parallel_type=:threads, callback = cb, tstops = tstops, saveat=0.001)
```

?

**Comment by ChrisRackauckas** [comment]
Well,

```julia
prob = ODEProblem(dyn_eq, u0, (0.0, tf))
monte_prob = MonteCarloProblem(prob)
sol = solve(monte_prob, Tsit5(), num_monte=100, parallel_type=:threads, callback = cb, tstops = tstops, saveat=0.001)
```

Yes. Then you can also do

```julia
prob = ODEProblem(dyn_eq, u0, (0.0, tf),callback = cb)
```

and then this is useful inside of the `prob_func` if you want to give a different callback to different trajectories.

**Comment by ronisbr** [comment]
Excellent! I think we can close this now.

Thank you very much for the prompt answer 👍
