### ISSUE TITLE
Scalling MonteCarloSummary

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/DiffEqMonteCarlo.jl#19]
Hi @ChrisRackauckas ,

What is the correct method to scale the results in MonteCarloSummary? Some computations from the differential equations must be in rads. However, it is good to plot them in degrees. Now, I am multiplying manually all the vectors in the MonteCarloSummary. Is there an automatic way to do this?

**Comment by ChrisRackauckas** [comment]
I'm not sure of an automatic way to do this.

**Comment by ChrisRackauckas** [comment]
I am going to close this since I think it may be over-engineering. Just multiplying the output is probably easiest.
