### ISSUE TITLE
What is the prob_func for Monte Carlo sims?

### ISSUE THREAD

**Issue by mcfefa** [JuliaDiffEq/DiffEqMonteCarlo.jl#20]
Hi Chris, in your Juliacon slides you have a section on Monte Carlo sims with a `prob_func` defined as below. However the [documentation](http://docs.juliadiffeq.org/stable/tutorials/sde_example.html#Monte-Carlo-Simulations-1) does not mention this `prob_func` keyword argument. Has this been deprecated / replaced with some other way of specifying the randomness? 

```
Monte Carlo Simulations
Many times you need to solve the same equation multiple times.
This is especially true for stochastic simulations.
```
```julia

In [29]:
pf_func = function (t,u,p,du)
  du[1] = p[1] * u[1] - p[2] * u[1]*u[2]
  du[2] = -3 * u[2] + u[1]*u[2]
end
pf = ParameterizedFunction(pf_func,[1.5,1.0])
pg_func = function (t,u,p,du)
  du[1] = p[1]*u[1]
  du[2] = p[2]*u[2]
end
pg = ParameterizedFunction(pg_func,[0.1,0.1])
prob = SDEProblem(pf,pg,[1.0,1.0],(0.0,10.0))

prob_func = function (prob,i)
  set_param_values!(prob.g,0.3rand(2))
  prob
end
monte_prob = MonteCarloProblem(prob,prob_func=prob_func)
sim = solve(monte_prob,SRIW1(),num_monte=10);
In [30]:
plot(sim,linealpha=0.6,color=:blue,vars=(0,1),title="The Timeseries'")
plot!(sim,linealpha=0.6,color=:red,vars=(0,2))
```

**Comment by ChrisRackauckas** [comment]
Hey,
  The page you linked was the stochastic differential equation tutorial which shows a quick preview of the Monte Carlo stuff but not all of the details. The Monte Carlo page is further down:

http://docs.juliadiffeq.org/stable/features/monte_carlo.html

It explains the `prob_func` in detail and gives some examples.
