### ISSUE TITLE
Variance reduction and other functionality

### ISSUE THREAD

**Issue by elevien** [JuliaDiffEq/DiffEqMonteCarlo.jl#4]
Are you interested in implementing variance reduction techniques such as multilevel Monte Carlo and importance sampling? In general, do you intend to keep DiffEqMonteCarlo.jl lightweight, or is the goal for this to develop into a fully functioning suite of Monte Carlo related tools? 
Thanks.

**Comment by ChrisRackauckas** [comment]
I separated it out as its own package for it to grow and include all sorts of variance reduction techniques, but I won't have time to do it, at least not for awhile. If anyone is willing to submit a PR I can help you get started.

**Comment by elevien** [comment]
Ok great. I'm planning to port a bunch of my research related code to Julia and contributing to this package would be a good place to start.

**Comment by ChrisRackauckas** [comment]
Cool. Let me know if you need any help.

Also, I just took a look at your profile (did we meet in Cambridge last summer?) and see you do systems biology. Just an FYI, I'm releasing parts for doing/mixing Gillespie-type simulations, along with MultiScaleModels.jl for developing, well, multi-scale models. These should be out by next week. I'm not sure if these need to be handled differently for variance-reduction techniques, but they will have a different problem type so it can be handled by dispatch.

**Comment by elevien** [comment]
Yeah, I believe we did meet at Cambridge! I was actually about to ask if you were planning to include methods for PDMPs/Jump diffusions when I noticed JumpDiffEq.jl. I'm just getting started with Julia, but pretty much all computational aspects of my research fall under the umbrella of problems handled by JuliaDiffEq, so I'll do my best to integrate my code.

**Comment by ChrisRackauckas** [comment]
An interface for defining and dispatching on new MonteCarloAlgorithms was added so that MonteCarloProblem can be used for these kinds of things in addition to just parallel solving.

**Comment by ChrisRackauckas** [comment]
These will now be handled as other EnsembleAlgs
