### ISSUE TITLE
trajectory averages

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaDiffEq/DiffEqMonteCarlo.jl#9]
It would be great to have some basic trajectory averaging functions. A typical operation that one needs in physics is to save a fairly high resolution time series for a number of different complex valued fields, and then compute a trajectory average at each time point. In phase space methods for quantum systems, for example, there is (at least typically, there are some exceptions) no physical interpretation of single trajectories, so we are mostly interested in weak convergence of ensemble averages.

Along the same lines, two-time correlation functions, computed as ensemble averages in time, but with a variable shift of time for one (or more) of the fields would be a nice thing to have ready access to. 

Is there any julia module for doing these kinds of averages?

**Comment by ChrisRackauckas** [comment]
Julia has a `mean(f::Function,v)` which will apply the function to each element of `v` take the mean. I think you can make `f` an anonymous function over `getindex`, like `(sol) -> sol[5]` to take the mean at the 5th timepoint. For two-time correlations, you can use that to generate two arrays, one for the values at each of the timepoints, and call a correlation function between two arrays.

Can you give those a try? If those things work we can specialize some functions on `AbstractMonteCarloSolution`. For example:

```julia
mean(v::AbstractMonteCarloSolution) # Returns mean at each timepoint
mean(v::AbstractMonteCarloSolution,i) # Returns the mean at the ith timestep
mean(v::AbstractMonteCarloSolution,t,Val{:interp}) # Returns the mean at time `t`. Requires interpolation
cov(v::AbstractMonteCarloSolution,i,j) # Returns the correlation between steps i and j
cov(v::AbstractMonteCarloSolution,ti,tj,Val{:interp}) # Returns the correlation between timepoints `ti` and `tj`. Requires interpolation
cor(...) # Extend cov functions to correlations
```

I think those would be very handy to have, and not hard to implement.

**Comment by ChrisRackauckas** [comment]
Made a bunch of stuff for this, including some nice plots.

http://docs.juliadiffeq.org/latest/features/monte_carlo.html#Analyzing-a-Monte-Carlo-Experiment-1

**Comment by AshtonSBradley** [comment]
Great, I'll check it out!
